// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqVQGnXMPcTPBNGqFV3jy-Q8I_qCOyJU',
    appId: '1:663064812721:web:4f4e0ad2f78e7c8f83d690',
    messagingSenderId: '663064812721',
    projectId: 'market-aa853',
    authDomain: 'market-aa853.firebaseapp.com',
    storageBucket: 'market-aa853.appspot.com',
    measurementId: 'G-YY1S6X1K3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-qtMuo4dqyGYs33ckGR1dQfXmKIz7OTo',
    appId: '1:663064812721:android:049711e946f2699383d690',
    messagingSenderId: '663064812721',
    projectId: 'market-aa853',
    storageBucket: 'market-aa853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8uzlFAJHIlr2uRvmHO9ifsJCqGt8lY8',
    appId: '1:663064812721:ios:1e857eb4f6898fa083d690',
    messagingSenderId: '663064812721',
    projectId: 'market-aa853',
    storageBucket: 'market-aa853.appspot.com',
    iosBundleId: 'com.example.market2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8uzlFAJHIlr2uRvmHO9ifsJCqGt8lY8',
    appId: '1:663064812721:ios:1e857eb4f6898fa083d690',
    messagingSenderId: '663064812721',
    projectId: 'market-aa853',
    storageBucket: 'market-aa853.appspot.com',
    iosBundleId: 'com.example.market2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOqVQGnXMPcTPBNGqFV3jy-Q8I_qCOyJU',
    appId: '1:663064812721:web:583af3467d147a9c83d690',
    messagingSenderId: '663064812721',
    projectId: 'market-aa853',
    authDomain: 'market-aa853.firebaseapp.com',
    storageBucket: 'market-aa853.appspot.com',
    measurementId: 'G-94GSBR4QCZ',
  );
}
